#!/bin/bash

function tg_sendText() {
curl -s "https://api.telegram.org/bot$BOT_TOKEN/sendMessage" \
-d "parse_mode=html" \
-d text="${1}" \
-d chat_id=$CHAT_ID \
-d "disable_web_page_preview=true"
}

# I'm collecting ccache for all ROMs that I build inorder to speed up all future updates that I will release for those ROMs.
# So when a new build will upload ccache, it should not overwrite the ccache i saved for another ROM!
# Therefore, I'm using the branch on which Cirrus CI is running to rename the ccache.tar files before uploading them.
# For e.g, if Cirrus CI is running on branch "sakura-arm64", the compressed ccache will be renamed to "sakura-arm64_ccache.tar.gz" and uploaded.
# The upload_ccache script will be amended as needed to properly extract the ccache to the right folder.
CCACHE_FILE="$CIRRUS_BRANCH""_ccache.tar.gz"

mkdir -p ~/.config/rclone
echo "$rclone_config" > ~/.config/rclone/rclone.conf # Write rclone config found from env variable, so that cloud storage can be used to upload ccache

tg_sendText "Downloading Ccache"

# So, I got upto 45% build complete for 1 hr 45 mins for first build (without any ccache)
# I got upto 97% build complete for 1hr 45 mins for second build (used 1st ccache from 1st build)

## My ccache are currently stored on my drive and its public, which means you can use my ccache if you are building the same rom as I have built but for a different device. You can view what ccaches i have at https://ccache.chatur27.workers.dev/

## If you use the below method 1, you will be able to download my ccache. I have not tested method 2. Please note that method 1 uses GDIndex and it has slower download speed than Google Drive. You will probably need to adjust the timeout for build2.sh script so that you get enough time to upload your updated ccache to your OWN Google Drive.


## Uncomment this section and comment lines 40 and 41 to use METHOD 1

# METHOD 1: Download using aria2c:
# Where ccache is located, use your own if you don't want to use my "prebuilt ccaches" xD
# cd /tmp
# url=https://ccache.chatur27.workers.dev/$CCACHE_FILE
# time aria2c $url -x16 -s50 # Using aria2c for speed haha, ccache will be at /tmp/$CCACHE_FILE

# METHOD 2: Download using Google Drive direcly (I have a premium account..HAHA):
time rclone copy aosp:$CCACHE_FILE /tmp/
cd /tmp # Where ccache has been downloaded


mv $CCACHE_FILE ccache.tar.gz # Rename back to original folder name before extracting
time tar xf ccache.tar.gz  # Extract ccache so ci can use it
rm -rf ccache.tar.gz # Remove unnecessary downloaded file, it will speed up the upload ccache process

tg_sendText "Ccache downloaded sucessfully"
