#!/bin/bash

function tg_sendText() {
curl -s "https://api.telegram.org/bot$BOT_TOKEN/sendMessage" \
-d "parse_mode=html" \
-d text="${1}" \
-d chat_id=$CHAT_ID \
-d "disable_web_page_preview=true"
}

mkdir -p ~/.config/rclone
echo "$rclone_config" > ~/.config/rclone/rclone.conf # Write rclone config found from env variable, so that cloud storage can be used to upload ccache

tg_sendText "Downloading Ccache.."

# So, I got upto 45% build complete for 1 hr 45 mins for first build (without any ccache)
# I got upto 97% build complete for 1hr 45 mins for second build (used 1st ccache from 1st build)

# METHOD 1: Download using aria2c:
# url=https://roms.chatur27.workers.dev/ccache.tar.gz # Where ccache is located, use your own.
# time aria2c $url -x16 -s50 # Using aria2c for speed haha, ccache will be at /tmp/ccache.tar.gz since my file name is ccache.tar.gz

# METHOD 2: Download using Google Drive direcly (I have a premium account..HAHA):
time rclone copy aosp:ccache.tar.gz /tmp/

cd /tmp # Where cccahe has been downloaded
time tar xf ccache.tar.gz  # Extract ccache so ci can use it
rm -rf ccache.tar.gz # Remove unnecessary downloaded file, it will speed up the upload ccache process

tg_sendText "Ccache downloaded sucessfully"
