#!/bin/bash

MANIFEST=
BRANCH=
# ADDITIONAL_MANIFEST=
# ADDITIONAL_BRANCH=

function tg_sendText() {
curl -s "https://api.telegram.org/bot$BOT_TOKEN/sendMessage" \
-d "parse_mode=html" \
-d text="${1}" \
-d chat_id=$CHAT_ID \
-d "disable_web_page_preview=true"
}

# Set up github's priviledged access
mkdir -p ~/.ssh
chmod 700 ~/.ssh
echo "$id_rsa" > ~/.ssh/id_rsa
echo "$id_rsa_pub" > ~/.ssh/id_rsa.pub
chmod 400 ~/.ssh/id_rsa
git config --global user.email "$user_email"
git config --global user.name "$user_name"
eval "$(ssh-agent -s)"
ssh-add ~/.ssh/id_rsa
echo "$known_hosts" > ~/.ssh/known_hosts


mkdir -p /tmp/rom # Where to sync source
cd /tmp/rom

tg_sendText "Downloading sources.."

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice. Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
repo init --no-repo-verify --depth=1 -u $MANIFEST -b $BRANCH -g default,-device,-mips,-darwin,-notdefault

# Clone local manifest! So that no need to manually git clone repos or change hals, you can use normal git clone or rm and re clone, they will cost little more time, and you may get timeout! Let's make it quit and depth=1 too.
#git clone $ADDITIONAL_MANIFEST --depth 1 -b $ADDITIONAL_BRANCH .repo/local_manifests
mv /tmp/ci/local_manifests /tmp/rom/.repo/

# Try with -j22 first, if fails, it will try again with -j8
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 22 || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 8

rm -rf .repo # lets remove unnecessary things, so that no storage issue can occur

tg_sendText "Repo Sync Completed!"
