#!/bin/bash

function tg_sendText() {
curl -s "https://api.telegram.org/bot$BOT_TOKEN/sendMessage" \
-d "parse_mode=html" \
-d text="${1}" \
-d chat_id=$CHAT_ID \
-d "disable_web_page_preview=true"
}

CCACHE_FILE="$CIRRUS_BRANCH""_ccache.tar.gz"

cd /tmp

tg_sendText "Uploading $CCACHE_FILE to Drive.."

# Compress function with pigz for faster compression
com () 
{ 
    tar --use-compress-program="pigz -k -$2 " -cf $1.tar.gz $1
}

time com ccache 1 # Compression level 1, its enough

# Rename file before uploading
mv ccache.tar.gz $CCACHE_FILE

time rclone copy $CCACHE_FILE aosp: -P # aosp is my rclone config name (first line without [] of ~/.config/rclone/rclone.conf file from rclone setup done on pc)

tg_sendText "Sucessfully uploaded ccache to Drive.."
